language: python


python:
  - "3.6"

os:
  - linux

env:
  - ENV=CI

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p "$HOME"/miniconda
  - source "$HOME"/miniconda/etc/profile.d/conda.sh
  - conda config --set always_yes yes --set changeps1 no --set auto_update_conda false
  - export LANG=en_US.UTF-8
  - export COVERAGE_DIR=":$HOME/htmlcov"
  - pip install -r requirements.txt
  - printenv | sort
  - conda install gcc_linux-64 gxx_linux-64 -c anaconda

# command to run tests
script: pytest --log-cli-level=ERROR

after_success:
  - codecov

